config:
    github_token: ${GITHUB_TOKEN}
    github_repository: ${GITHUB_REPOSITORY}
    hetzner_token: ${HETZNER_TOKEN}
    ssh_key: "~/.ssh/id_rsa.pub"
    #additional_ssh_keys:
    max_runners: 10
    recycle: true
    end_of_life: 50
    default_image: "x86:system:ubuntu-22.04"
    default_server_type: cpx11
    #default_location:
    workers: 10
    #setup_script:
    #startup_x64_script:
    #startup_arm64_script:
    max_powered_off_time: 60
    max_unused_runner_time: 120
    max_runner_registration_time: 120
    max_server_ready_time: 120
    scale_up_interval: 15
    scale_down_interval: 15
    debug: false
    # cloud service deployment configuration
    cloud:
        server_name: "github-runners"
        deploy:
            server_type: cpx11
            image: "x86:system:ubuntu-22.04"
            #location:
            #setup_script:
    # standby runners groups configuration
    standby_runners:
        - labels:
            - type-cpx21
          count: 3
          replenish_immediately: true
    # logging module config
    logger_config:
        version: 1
        disable_existing_loggers: false
        formatters:
            standard:
                format: "%(asctime)s %(levelname)-7s %(message)-60s %(funcName)s"
                datefmt: "%m/%d/%Y %I:%M:%S %p"
        handlers:
            default:
                level: INFO
                formatter: standard
                class: logging.StreamHandler
                stream: "ext://sys.stdout"
        loggers:
            testflows.github.runners:
                level: INFO
                handlers:
                    - default
